name: Check URLs
on:
  pull_request:
  push:
  schedule:
    - cron: '55 16,17,18,19,20 * * *'

jobs:
  check-urls:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: urlstechie/urlchecker-action@master
      with:
        file_types: .md
